# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14rJrfxIoWrTe2hUpAK1VKXZv6QvWLijB
"""

import numpy as np
import cv2 as cv
import matplotlib.pyplot as plt


def histogram_equalization_manual(gray_image):
    """
    Ручная эквализация гистограммы по формуле:
    LUT[i] = 255 * sum_{j=0..i} Hist[j] / sum_{j=0..255} Hist[j]
    """

    # 1. Гистограмма
    hist = np.zeros(256, dtype=np.int32)
    for pixel in gray_image.flatten():
        hist[pixel] += 1

    # 2. Кумулятивная сумма
    cdf = np.cumsum(hist)

    # 3. LUT по формуле
    total_pixels = gray_image.size
    lut = np.round(255 * cdf / total_pixels).astype(np.uint8)

    # 4. Применение LUT
    equalized_image = lut[gray_image]

    return equalized_image, hist


def plot_histogram(image, title):
    hist = cv.calcHist([image], [0], None, [256], [0, 256])
    plt.plot(hist)
    plt.title(title)
    plt.xlim([0, 256])


def lab_2_histogram_equalization():
    # Загрузка изображения
    image = cv.imread('/lenna.png')

    # Перевод в оттенки серого
    gray = cv.cvtColor(image, cv.COLOR_BGR2GRAY)

    # Эквализация
    eq_image, hist_before = histogram_equalization_manual(gray)

    # Визуализация
    plt.figure(figsize=(12, 8))

    plt.subplot(2, 2, 1)
    plt.imshow(gray, cmap='gray')
    plt.title('Исходное изображение')
    plt.axis('off')

    plt.subplot(2, 2, 2)
    plt.imshow(eq_image, cmap='gray')
    plt.title('После эквализации')
    plt.axis('off')

    plt.subplot(2, 2, 3)
    plot_histogram(gray, 'Гистограмма исходного изображения')

    plt.subplot(2, 2, 4)
    plot_histogram(eq_image, 'Гистограмма после эквализации')

    plt.tight_layout()
    plt.show()


lab_2_histogram_equalization()